name: Build
on:
  pull_request:
  push:
    branches: [main, "testing/*"]
    tags: [v*]
jobs:
  build:
    runs-on: ubuntu-22.04 
    steps:
      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libwayland-client-dev wayland-protocols \
            libwayland-cursor-dev libxkbcommon-dev libpangocairo
      - uses: secondlife/action-autobuild@v3
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v3
