name: Build
on:
  pull_request:
  push:
    branches: [main, "testing/*"]
    tags: [v*]
jobs:
  build:
    runs-on: ubuntu-22.04 
    steps:
      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libasound2-dev libglu1-mesa-dev libwayland-dev \
            wayland-protocols libdbus-1-dev libxkbcommon-dev \
            libegl-dev libpangocairo-1.0-0 libopengl-dev \
            libpango1.0-dev libgtk-3-dev
      - uses: secondlife/action-autobuild@v3
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v3
